#!/bin/bash

echo "🚀 Deploying Monad Security Monitor Frontend to GitHub + Lovable"
echo "================================================================"
echo ""

echo "📋 Current Status:"
echo "✅ Git repository initialized"
echo "✅ 2 commits ready:"
echo "   - 93c417a: Initial commit with complete frontend"
echo "   - 4bbd229: Privacy update (removed specific site references)"
echo "✅ All files committed and clean working directory"
echo ""

echo "🔗 Next Steps:"
echo ""
echo "1️⃣ CREATE GITHUB REPOSITORY:"
echo "   Go to: https://github.com/new"
echo "   Repository name: monad-security-monitor-frontend"
echo "   Description: Real-time EIP-7702 attack detection for Monad testnet"
echo "   Visibility: Public (recommended for community project)"
echo "   ❌ DO NOT initialize with README, .gitignore, or license"
echo ""

echo "2️⃣ PUSH TO GITHUB:"
echo "   After creating the repository, run these commands:"
echo ""
echo "   # Add your GitHub repository as remote"
echo "   git remote add origin https://github.com/YOUR_USERNAME/monad-security-monitor-frontend.git"
echo ""
echo "   # Push your commits to GitHub"
echo "   git push -u origin main"
echo ""

echo "3️⃣ DEPLOY TO LOVABLE:"
echo "   Go to: https://lovable.dev"
echo "   - Click 'New Project'"
echo "   - Select 'Import from GitHub'"
echo "   - Choose: YOUR_USERNAME/monad-security-monitor-frontend"
echo "   - Lovable will auto-detect React + Vite project"
echo ""

echo "4️⃣ SET ENVIRONMENT VARIABLES:"
echo "   In Lovable dashboard, add:"
echo "   VITE_API_URL=https://your-backend-api.onrender.com"
echo ""

echo "5️⃣ DEPLOY:"
echo "   Click 'Deploy' in Lovable"
echo "   Your app will be live at: https://PROJECT_NAME.lovable.app"
echo ""

echo "🛡️ FEATURES READY:"
echo "✅ Real-time threat monitoring"
echo "✅ Wallet security scanner (no wallet connection required)"
echo "✅ Mobile-responsive design"
echo "✅ Known malicious contract detection"
echo "✅ Privacy-conscious messaging"
echo "✅ Community protection tools"
echo ""

echo "📞 Need help? Check the documentation files:"
echo "   - GITHUB-DEPLOYMENT.md (detailed GitHub integration guide)"
echo "   - DEPLOY-TO-LOVABLE.md (comprehensive Lovable deployment)"
echo "   - README.md (project overview and features)"
echo ""

echo "🎉 Ready to protect the Monad community!"
echo "================================================================"